# .github/workflows/build.yml
name: Build executables

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller
      - name: Package .exe
        run: |
          pyinstaller --onefile aimaFucker.py --distpath dist/windows --name aimaFucker.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/windows/aimaFucker.exe

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller
      - name: Package Linux binary
        run: |
          pyinstaller --onefile aimaFucker.py \
                      --distpath dist/linux \
                      --name aimaFucker
          chmod +x dist/linux/aimaFucker
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/linux/aimaFucker
